Models/Guest.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Guest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest()
        {
            this.guest_rest = new HashSet<guest_rest>();
            this.Occasions = new HashSet<Occasion>();
            this.Rooms = new HashSet<Room>();
            this.Packages = new HashSet<Package>();
            this.Reservations = new HashSet<Reservation>();
            this.Transportations = new HashSet<Transportation>();
            this.Trips = new HashSet<Trip>();
        }
    
        public int cust_id { get; set; }
        [Required]
        [Display(Name ="First Name")]
        public string Fname { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string Lname { get; set; }
        [Required]
        [Display(Name = "Email")]
        public string email { get; set; }
        [Required]
        [StringLength(20,MinimumLength =8,ErrorMessage ="Your password must be at least 8 characters and maximum 20")]
        public string password { get; set; }
        [Required]
        [Display(Name = "confirm password")]
        [Compare("password",ErrorMessage ="Passwords not matching")]
        public string confpassword { get; set; }
        [Required]
        [Display(Name = "Gender")]
        public string gender { get; set; }
        [Required]
        [Display(Name = "Nationality")]
        public string nationality { get; set; }
        public string address { get; set; }

        [Display(Name = "Birthdate")]
        public DateTime? birthdate { get; set; }

        [Display(Name = "Phone number")]
        public string phone_no { get; set; }
        public Nullable<int> points { get; set; }
        public string cardholder_name { get; set; }
        public string card_no { get; set; }
        public Nullable<int> cvv { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<guest_rest> guest_rest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Occasion> Occasions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Package> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transportation> Transportations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trip> Trips { get; set; }
    }
}

Controllers/GuestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class GuestsController : Controller
    {
        private Hotel_IPEntities db = new Hotel_IPEntities();

        // GET: Guests
        public ActionResult Index()
        {
            return View(db.Guests.ToList());
        }

        // GET: Guests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guest guest = db.Guests.Find(id);
            if (guest == null)
            {
                return HttpNotFound();
            }
            return View(guest);
        }

        // GET: Guests/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Guests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "cust_id,Fname,Lname,email,password,gender,nationality,address,birthdate,phone_no,points,cardholder_name,card_no,cvv,exp_date")] Guest guest)
        {
            if (ModelState.IsValid)
            {
                db.Guests.Add(guest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(guest);
        }

        // GET: Guests/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guest guest = db.Guests.Find(id);
            if (guest == null)
            {
                return HttpNotFound();
            }
            return View(guest);
        }

        // POST: Guests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "cust_id,Fname,Lname,email,password,gender,nationality,address,birthdate,phone_no,points,cardholder_name,card_no,cvv,exp_date")] Guest guest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(guest).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(guest);
        }

        // GET: Guests/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Guest guest = db.Guests.Find(id);
            if (guest == null)
            {
                return HttpNotFound();
            }
            return View(guest);
        }

        // POST: Guests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Guest guest = db.Guests.Find(id);
            db.Guests.Remove(guest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login([Bind(Include = "email,password")] Guest guest)
        {
            var rec = db.Guests.Where(x => x.email == guest.email && x.password == guest.password).ToList().FirstOrDefault();
            if (rec != null)
            {
                Session["username"] = rec.Fname;
                return RedirectToAction("Index","Home");
            }
            else
            {
                ViewBag.error = "Invalid User"; ;
                return View(guest);
            }
        }
        public ActionResult Signup()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Signup([Bind(Include = "Fname,Lname,email,password,gender,nationality,address,birthdate,phone_no")]Guest r)
        {
            if (ModelState.IsValid)
            {

                db.Guests.Add(r);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
                return View(r);
        }
    } 
}

Views/Guests/Create.cshtml
@model WebApplication4.Models.Guest

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Guest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Fname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Lname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nationality, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nationality, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nationality, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.birthdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.birthdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.points, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.points, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.points, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cardholder_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cardholder_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cardholder_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.card_no, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.card_no, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.card_no, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cvv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cvv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cvv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.exp_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.exp_date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.exp_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Guests/Delete.cshtml
@model WebApplication4.Models.Guest

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Guest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.points)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.points)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cardholder_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cardholder_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.card_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.card_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cvv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cvv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.exp_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.exp_date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Guests/Details.cshtml
@model WebApplication4.Models.Guest

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Guest</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Fname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nationality)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nationality)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.points)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.points)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cardholder_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cardholder_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.card_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.card_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cvv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cvv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.exp_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.exp_date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.cust_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Guests/Index.cshtml
@model IEnumerable<WebApplication4.Models.Guest>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Fname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nationality)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.birthdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone_no)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.points)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cardholder_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.card_no)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cvv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.exp_date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Fname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nationality)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.birthdate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phone_no)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.points)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cardholder_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.card_no)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cvv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.exp_date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.cust_id }) |
            @Html.ActionLink("Details", "Details", new { id=item.cust_id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.cust_id })
        </td>
    </tr>
}

</table>

Views/Guests/Login.cshtml
@model WebApplication4.Models.Guest

@{
    ViewBag.Title = "Login";
}
@{
    Layout = null;
}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

    <section class="vh-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-black">
                    <div class="d-flex flex-column align-items-center px-3 mt-3">
                        @using (Html.BeginForm())
                        {
                            <form style="width: 23rem;">

                                <h3 class="fw-normal mb-3 pb-1" style="letter-spacing: 1px;">Log in</h3>

                                <div class="form-outline mb-4">
                                    @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "form-label" })
                                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control form-control-lg" } })
                                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                                </div>

                                
                                <div class="form-outline mb-4">
                                    @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
                                    
                                        @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control form-control-lg", @type="password"} })
                                        @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
                                    
                                </div>

                                    <div class="pt-1 mb-4">
                                        <button class="btn btn-primary btn-lg btn-block" type="submit">Login</button>
                                        <br />
                                        @ViewBag.error
                                    </div>

                                    <p>Don't have an account? @Html.ActionLink("Register here", "Signup", "Guests", null, new { @class = "link-info" })</p>

                          </form>
                        }
                    </div>
                </div>
                <div class="col-sm-6 px-0 d-none d-sm-block">
                    <img src="~/images/hotel_2 (2) (1).jpg"
                         alt="Signup image" class="w-100 vh-100 img-fluid" >
                </div>
            </div>
        </div>
    </section>
    <</body></html>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/bootstrap")
    }